const $=s=>document.querySelector(s);let config={},current=null,filter='all',polling=null;
const names={seeking:'明确求推荐',switching:'正在找替代',pain:'具体困扰',noise:'无关 / 推广'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options){const r=await fetch(path,options);const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function connection(){const p=$('#provider').value;$('#import-box').hidden=p!=='import';const needed=['BLOCKRUN_API_KEY','TYPESAFE_API_KEY',...({twitterapi:['TWITTERAPI_KEY'],x:['X_BEARER_TOKEN']}[p]||[])];const missing=needed.filter(k=>!config.configured?.[k]);$('#connection').textContent=missing.length?'需配置：'+missing.join('、'):p==='exa'?'已配置 · 网页索引不保证收录 X 原帖':'接口已配置 · 就绪';$('#connection').className='notice'+(!missing.length?' ready':'');}
async function history(){const runs=await api('/api/runs');$('#history').innerHTML='<option value="">选择一次历史运行</option>'+runs.map(r=>`<option value="${esc(r.id)}">${esc(r.company)} · ${esc(r.status)} · ${esc(r.started_at?.slice(0,16))}</option>`).join('');}
function render(run,replay=false){current=run;if(!run)return;$('#replay-label').textContent=replay?'历史回放 · 不会发起新的 API 请求':'';$('#board-title').textContent=run.company?.name?`${run.company.name} 的潜在线索`:'你的下一段对话';$('#error').textContent=run.error||'';const posts=run.posts||[];const cost=run.cost;const amount=cost?`$${(cost.reported_usd+cost.estimated_usd).toFixed(4)}`:'—';$('#stats').innerHTML=[[run.valid_count??'—','有效帖子'],[posts.filter(p=>p.priority==='review').length,'值得查看'],[run.jev_seconds!=null?run.jev_seconds+'s':'—','Jev 判断耗时'],[amount,cost?.unknown_calls?'已知费用 · 另有未知费用':'含估算费用']].map(([n,l])=>`<div><strong>${esc(n)}</strong><span>${esc(l)}</span></div>`).join('');const stages=['company','search','classify','draft'];$('#progress').innerHTML=['① 理解产品','② 搜索原帖','③ Jev 筛选','④ 整理线索'].map((s,i)=>`<span class="${run.stage===stages[i]?'working':''}">${s}</span>`).join('')+`<span>${esc(run.status==='running'?run.events?.at(-1)?.message:run.status)}</span>`;$('#warnings').innerHTML=(run.warnings||[]).map(w=>`<div class="warning">${esc(w)}</div>`).join('');$('#export').hidden=!run.id;if(run.id)$('#export').href='/api/runs/'+encodeURIComponent(run.id)+'.csv';const shown=posts.filter(p=>filter==='all'||p.priority===filter||p.category===filter);$('#posts').innerHTML=shown.length?shown.map(p=>`<article class="card"><div class="card-top"><span class="avatar">${esc(p.author[0]?.toUpperCase())}</span><div><div class="author">@${esc(p.author)}</div><div class="date">${esc(p.created_at.slice(0,16))} UTC</div></div><span class="badge ${p.priority==='excluded'?'excluded':''}">${esc(names[p.category])}</span></div><blockquote>${esc(p.text)}</blockquote><div class="card-meta"><span>优先级 ${p.score}/100</span><span>匹配 ${(p.fit*100).toFixed(0)}%</span><span>标签置信度 ${(p.confidence*100).toFixed(0)}%</span><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">查看原帖 ↗</a></div>${p.suggestion?`<div class="details"><p><strong>匹配依据：</strong>${esc(p.suggestion.reason)}</p><p><strong>原文证据：</strong>“${esc(p.suggestion.evidence)}”</p><p><strong>需要确认：</strong>${esc(p.suggestion.check)}</p><details><summary>查看回复草稿</summary><div class="draft">${esc(p.suggestion.draft)}</div></details></div>`:''}</article>`).join(''):`<div class="empty"><div class="empty-icon">◎</div><h3>${run.status==='running'?'正在寻找真实需求…':run.status==='empty'?'没有获得符合条件的原帖':run.status==='failed'?'这一轮尚未完成':'这个分类暂无线索'}</h3><p>${run.status==='empty'?'尝试调整搜索词，或配置专用 X 数据入口。':'结果会按实际返回的数据展示。'}</p></div>`;$('#audit').innerHTML=`<pre>${esc(JSON.stringify({mode:run.mode,provider:run.provider,models:run.models,events:run.events,searches:run.searches,rejected:run.rejected,cost:run.cost,calls:run.calls},null,2))}</pre>`;}
$('#provider').addEventListener('change',connection);$('#filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));if(current)render(current,$('#replay-label').textContent!=='');});
$('#history').addEventListener('change',async e=>{if(!e.target.value)return;try{render(await api('/api/runs/'+encodeURIComponent(e.target.value)),true);}catch(e){$('#error').textContent=e.message;}});
async function poll(){try{const s=await api('/api/status');if(s.run)render(s.run);$('#start').disabled=s.busy;if(!s.busy){clearInterval(polling);polling=null;history();}}catch(e){clearInterval(polling);$('#error').textContent='连接中断，请刷新查看运行状态；不要重复提交。';}}
$('#run-form').addEventListener('submit',async e=>{e.preventDefault();$('#error').textContent='';try{const options={url:$('#url').value,brief:$('#brief').value,provider:$('#provider').value,days:Number($('#days').value),limit:Number($('#limit').value)};const qs=$('#queries').value.split('\n').map(s=>s.trim()).filter(Boolean);if(qs.length)options.queries=qs;if(options.provider==='import'){const f=$('#import-file').files[0];if(!f)throw Error('请选择原帖 JSON 文件');if(f.size>1500000)throw Error('导入文件不能超过 1.5 MB');options.posts=JSON.parse(await f.text());}$('#start').disabled=true;await api('/api/run',{method:'POST',headers:{'Content-Type':'application/json','X-SignalDesk-Token':config.token},body:JSON.stringify(options)});polling=setInterval(poll,1000);await poll();}catch(e){$('#error').textContent=e.message;$('#start').disabled=false;}});
async function init(){try{config=await api('/api/config');if(config.configured.TWITTERAPI_KEY)$('#provider').value='twitterapi';else if(config.configured.X_BEARER_TOKEN)$('#provider').value='x';connection();await history();const state=await api('/api/status');if(state.run)render(state.run);if(state.busy){$('#start').disabled=true;polling=setInterval(poll,1000);}}catch(e){$('#error').textContent=e.message;}}init();
